### ISSUE TITLE
Container failed to Start

### ISSUE THREAD

**Issue by hierony94** [ewoutp/stunnel-docker#1]
Hello @ewoutp 

I'm customizing your Dockerfile to be like this (I copy stunnel.conf & certificate)

```
FROM alpine:3.2

RUN echo "http://dl-3.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
&& apk add -U stunnel ca-certificates \
&& rm -rf /var/cache/apk/*

COPY stunnel.conf /etc/stunnel/stunnel.conf
COPY mail.pem /etc/stunnel/mail.pem

ENTRYPOINT [ "/usr/bin/stunnel" ]
```

But when I'm run `docker run image_name` I don't show any response in my terminal. And when I see `docker ps -a` the container was in Exited state. I'm trying to see the log using `docker logs`, but it show anything too.

Can you help me realize in what way I do it wrong.

Thanks.

**Comment by hierony94** [comment]
**Updated**

After I add `-it` option when run docker run, somehow it give the log.
The log looks like here :

```
stunnel: LOG5[ui]: stunnel 5.32 on x86_64-alpine-linux-musl platform
stunnel: LOG5[ui]: Compiled/running with OpenSSL 1.0.2h  3 May 2016
stunnel: LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
stunnel: LOG5[ui]: Reading configuration from file /etc/stunnel/stunnel.conf
stunnel: LOG5[ui]: UTF-8 byte order mark not detected
stunnel: LOG4[ui]: Service [smtp-tls-wrapper] needs authentication to prevent MITM attacks
stunnel: LOG5[ui]: Configuration successful
```

But when I see the docker container, the status is Exited.

**Comment by ewoutp** [comment]
Hi @hierony94,

Try including `foreground = yes` in your stunnel config file.

**Comment by hierony94** [comment]
Hi @ewoutp,

Thanks, It works like a charm.
